apiVersion: apps/v1
kind: Deployment
metadata:
  name: entities-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entities-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: entities-service
    spec:
      containers:
      - name: entities-service
        image: scaiweuacrdev.azurecr.io/entitiesservice:latest                                                                                                             
        ports:
        - containerPort: 8080